name: Java CI with Maven

on:
  push:
    # 分支
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Running Java ${{ matrix.java }} compile
    steps:
      - name: 在服务器上执行 java -jar，请确保服务器安装了 JDK
        uses: fifsky/ssh-action@master
        with:
          command: cd /opt/springboot
          host: ${{ secrets.HOST }}
          user: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.PORT }}
          args: "-tt -vvv"
